apiVersion: v1
kind: ConfigMap
metadata:
  name: db-env
data:
  DB_USERNAME: "ct_admin"
  DB_NAME: "geoconnections"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  # PERSON_SERVICE_ENDPOINT: "http://person-api:5000/"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-env
  namespace: default
data:
  KAFKA_URL: my-release-kafka.default.svc.cluster.local:9092 
  KAFKA_TOPIC: "locations"
  KAFKA_PORT: "9092"










