apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-location-event-prod-api
  name: udaconnect-location-event-prod-api
spec:
  ports:
  - name: "5000"
    port: 5005 
    targetPort: 5005
    nodePort: 30003 
  selector:
    service: udaconnect-location-event-prod-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-location-event-prod-api
  name: udaconnect-location-event-prod-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-location-event-prod-api
  template:
    metadata:
      labels:
        service: udaconnect-location-event-prod-api
    spec:
      containers:
      - image: myaxu/udaconnect-location-event-prod-api:latest
        name: udaconnect-location-event-prod-api
        imagePullPolicy: Always
        env:
        - name: KAFKA_URL 
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_URL 
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_TOPIC
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT              
      restartPolicy: Always
